OPPO_HTTP_PORT = 436
OPPO_TELNET_PORT = 23
OPPO_REMOTE_LOGIN_PORT = 7624
OPPO_REMOTE_LOGIN_MESSAGE = "NOTIFY OREMOTE LOGIN"
DEFAULT_OPPO_REQUEST_TIMEOUT_SECONDS = 5
DEFAULT_OPPO_SIGN_IN_TIMEOUT_SECONDS = 3
